# Generated by Django 3.1.13 on 2021-08-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='qusetion',
            new_name='question',
        ),
    ]
