# Generated by Django 3.1.13 on 2021-08-11 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210811_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qusetion_text',
            new_name='question_text',
        ),
    ]
